### ISSUE TITLE
Microsoft Defender Antivirus detected a virus in version 1.3.1

### ISSUE THREAD

**Issue by Reniel80** [TonimatasDEV/PacketFixer#36]
packetfixer-fabric-1.3.1-1.19-to-1.20.1.jar
Trojan:Script/Wacatac.B!ml Detected by Microsoft Defender Antivirus.
Downloaded from Modrinth and Curseforge.

**Comment by TonimatasDEV** [comment]
> packetfixer-fabric-1.3.1-1.19-to-1.20.1.jar Trojan:Script/Wacatac.B!ml Detected by Microsoft Defender Antivirus. Downloaded from Modrinth and Curseforge.

I think is a false positive:
https://www.virustotal.com/gui/file/41402d4e287fccd444533af7a2bf52c7e68dc8bab85871636ab567fff46ce175/detection
https://www.filescan.io/uploads/6624e2ba14ba3ce82897efdf/reports/bae342fd-2c96-4b77-bc00-dd8e739ef941/overview

Filescan.IO is suspicious because it could be a file masquerading as another file. I guess because of the class names. But you can decompile it yourself and see it or build it direcly with the source code.
